---
- hosts: all
  become: True
  tasks:
   - name: update repo
     command: "apt-get update"
   - name: to install httpd pkg
     apt: name=apache2 state=latest
   - name: Service reunning
     service: name=apache2 state=started enable=yes
